### ISSUE TITLE
python tests: set_int_max_str_digits

### ISSUE THREAD

**Issue by Blind4Basics** [hobovsky/katasniplib#18]
**Title:** set_int_max_str_digits

**Languages:** python

**Summary:** Allow conversion of huge int values to strings in tests feedback (update to 3.11)

**Tags:** ?

### Kata snippets:

- [x] submission tests
- [ ] example tests
- [ ] complete solution
- [ ] solution setup
- [ ] preloaded code
- [ ] description

### Markdown

`````text
```python
import sys
sys.set_int_max_str_digits(0)
```
`````

**Comment by hobovsky** [comment]
Thanks!
